DROP SEQUENCE INDIVIDUALSEQ;
DROP TABLE INDIVIDUAL;

CREATE SEQUENCE INDIVIDUALSEQ;

CREATE TABLE INDIVIDUAL(
	INDIVIDUAL_NO NUMBER PRIMARY KEY,
	PROFILE_NO NUMBER NOT NULL,
	INDIVIDUAL_ID VARCHAR2(500) NOT NULL,
	INDIVIDUAL_TITLE VARCHAR2(1000)  NOT NULL,
	INDIVIDUAL_CONTENT VARCHAR2(4000)  NOT NULL,
	INDIVIDUAL_MDATE VARCHAR2(12)  NOT NULL,
	INDIVIDUAL_REGDATE DATE  NOT NULL
);


INSERT INTO INDIVIDUAL
VALUES(INDIVIDUALSEQ.NEXTVAL, 1, 'cine', 'cine입니다', '프로젝트 화이팅!!', '202103210110', SYSDATE);

INSERT INTO INDIVIDUAL
VALUES(INDIVIDUALSEQ.NEXTVAL, 1, 'cine', 'cine입니다', '프로젝트 화이팅!!', '202103221010', SYSDATE);

INSERT INTO INDIVIDUAL
VALUES(INDIVIDUALSEQ.NEXTVAL, 1, 'cine', 'cine입니다', '프로젝트 화이팅!!', '202103231210', SYSDATE);

INSERT INTO INDIVIDUAL
VALUES(INDIVIDUALSEQ.NEXTVAL, 1, 'cine', 'cine입니다', '프로젝트 화이팅!!', '202110101010', SYSDATE);


SELECT INDIVIDUAL_NO, PROFILE_NO, INDIVIDUAL_ID, INDIVIDUAL_TITLE, INDIVIDUAL_CONTENT, INDIVIDUAL_MDATE, INDIVIDUAL_REGDATE
FROM INDIVIDUAL
WHERE INDIVIDUAL_ID = 'cine'
AND SUBSTR(INDIVIDUAL_MDATE, 1, 8) = '20211010'
ORDER BY INDIVIDUAL_NO DESC;


