DROP SEQUENCE PAYMENTSEQ;
DROP TABLE PAYMENT;

CREATE SEQUENCE PAYMENTSEQ;

CREATE TABLE PAYMENT(
	PAYMENT_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(50) NOT NULL,
	PAYMENT_ACOUNT NUMBER NOT NULL,
	PAYMENT_DATE DATE NOT NULL,
	CONSTRAINT PAYMENT_UK UNIQUE(MEMBER_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

INSERT INTO PAYMENT
VALUES(PAYMENTSEQ.NEXTVAL, 'qweqwe', '9900', SYSDATE);