DROP TABLE MEMBER;
DROP TABLE MEMBER_ROLE;
DROP TABLE POST;
DROP TABLE COMMENT;
DROP TABLE IMAGE;
DROP TABLE SCRAP;
DROP TABLE MESSAGE;
DROP TABLE FOLLOW;
DROP TABLE CALENDAR;
DROP TABLE NOTIFICATION;
DROP TABLE COMMENT1;

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE POST_SEQ;
DROP SEQUENCE COMMENT_SEQ;
DROP SEQUENCE IMAGE_SEQ;
DROP SEQUENCE FOLLOW_SEQ;
DROP SEQUENCE CALENDAR_SEQ;
DROP SEQUENCE MESSAGE_SEQ;
DROP SEQUENCE SCRAP_SEQ;
DROP SEQUENCE NOTIFICATION_SEQ;

ALTER TABLE COMMENT1 DROP CONSTRAINT COMMENT_PK1;

SELECT * FROM MEMBER;
SELECT * FROM POST;
SELECT * FROM COMMENT;
SELECT * FROM IMAGE;

SELECT * FROM ALL_CONSTRAINTS;

DROP SEQUENCE POST_SEQ;

SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE POST_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO POST
VALUES(POST_SEQ.NEXTVAL, POST_USER_NO,POST_ID,POST_NO,POST_BOARD_NAME,POST_CATEGORY_NAME,POST_TITLE,POST_CONTENT
		,POST_MDATE,POST_REGDATE,POST_HIT,POST_COMMENT_HIT,POST_LIKE,POST_DELFLAG,POST_LATITUDE,POST_LONGITUDE);

ALTER TABLE POST
ADD CONSTRAINT FK_POST_POST_USER_NO_MEMBER_ME FOREIGN KEY (POST_USER_NO)
REFERENCES MEMBER (MEMBER_NO);

CREATE TABLE COMMENT(
    COMMENT_ID          NUMBER            NOT NULL, 
    COMMENT_POST_ID     NUMBER            NOT NULL, 
    COMMENT_NO          NUMBER            NOT NULL, 
    COMMENT_REPLY_NO    NUMBER            NULL, 
    COMMENT_CONTENT     VARCHAR2(4000)    NOT NULL, 
    COMMENT_WRITER      VARCHAR2(500)     NOT NULL, 
    COMMENT_REGDATE     DATE              NOT NULL, 
    COMMENT_DELFLAG     VARCHAR2(2)       NOT NULL, 
    CONSTRAINT COMMENT_PK PRIMARY KEY (COMMENT_ID)
);

INSERT INTO ACCOMPANYBOARD
VALUES(1, 'TEST TITLE');

SELECT ACCOMPANYBOARDSEQ.NEXTVAL, POST_ID, POST_TITLE
FROM ACCOMPANYBOARD;

