DROP TABLE ACCOMPANYBOARD;
DROP TABLE PHOTOREVIEWBOARD;
DROP TABLE NOTICEBOARD;

CREATE SEQUENCE ACCOMPANYBOARDSEQ;

CREATE TABLE ACCOMPANYBOARD(
	POST_ID NUMBER PRIMARY KEY,
	POST_TITLE VARCHAR2(500)
);

INSERT INTO ACCOMPANYBOARD
VALUES(1, 'TEST TITLE');

SELECT ACCOMPANYBOARDSEQ.NEXTVAL, POST_ID, POST_TITLE
FROM ACCOMPANYBOARD;

CREATE SEQUENCE PHOTOREVIEWBOARDSEQ;

CREATE TABLE PHOTOREVIEWBOARD(
	SEQ NUMBER PRIMARY KEY,

);

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICEBOARD(
	SEQ NUMBER PRIMARY KEY,
	
	
);